included:
    - Qiitable/
    - Domain

excluded:
    - Carthage

disabled_rules:
    - trailing_whitespace
    - nesting
    - cyclomatic_complexity
    - multiple_closures_with_trailing_closure
    - function_body_length
    - file_length
    - type_body_length
    - identifier_name
    - implicit_getter
    - orphaned_doc_comment
    - function_parameter_count

line_length:
    - 250
    - 300
