///
/// @Generated by Mockolo
///



import Combine
import Foundation


public class ItemRepositoryMock: ItemRepository {
    public init() { }


    public var fetchCallCount = 0
    public var fetchHandler: ((Int, @escaping (Swift.Result<[Item], Error>) -> Void) -> ())?
    public func fetch(page: Int, completion: @escaping (Swift.Result<[Item], Error>) -> Void)  {
        fetchCallCount += 1
        if let fetchHandler = fetchHandler {
            fetchHandler(page, completion)
        }
        
    }

    public var searchCallCount = 0
    public var searchHandler: ((String, Int, @escaping (Swift.Result<[Item], Error>) -> Void) -> ())?
    public func search(query: String, page: Int, completion: @escaping (Swift.Result<[Item], Error>) -> Void)  {
        searchCallCount += 1
        if let searchHandler = searchHandler {
            searchHandler(query, page, completion)
        }
        
    }
}

