///
/// @Generated by Mockolo
///



import Foundation


class HomeRouterMock: HomeRouter {
    init() { }


}

class RootRouterMock: RootRouter {
    init() { }


    var makeHomeViewCallCount = 0
    var makeHomeViewHandler: (() -> (HomeView))?
    func makeHomeView() -> HomeView {
        makeHomeViewCallCount += 1
        if let makeHomeViewHandler = makeHomeViewHandler {
            return makeHomeViewHandler()
        }
        fatalError("makeHomeViewHandler returns can't have a default value thus its handler must be set")
    }

    var makeSearchViewCallCount = 0
    var makeSearchViewHandler: (() -> (SearchView))?
    func makeSearchView() -> SearchView {
        makeSearchViewCallCount += 1
        if let makeSearchViewHandler = makeSearchViewHandler {
            return makeSearchViewHandler()
        }
        fatalError("makeSearchViewHandler returns can't have a default value thus its handler must be set")
    }
}

