///
/// @Generated by Mockolo
///



import Foundation


class HomeUseCaseMock: HomeUseCase {
    init() { }


    var fetchCallCount = 0
    var fetchHandler: ((Int, @escaping (Swift.Result<[Item], Error>) -> Void) -> ())?
    func fetch(page: Int, completion: @escaping (Swift.Result<[Item], Error>) -> Void)  {
        fetchCallCount += 1
        if let fetchHandler = fetchHandler {
            fetchHandler(page, completion)
        }
        
    }
}

class SearchListUseCaseMock: SearchListUseCase {
    init() { }


    var fetchCallCount = 0
    var fetchHandler: ((String, Int, @escaping (Swift.Result<[Item], Error>) -> Void) -> ())?
    func fetch(query: String, page: Int, completion: @escaping (Swift.Result<[Item], Error>) -> Void)  {
        fetchCallCount += 1
        if let fetchHandler = fetchHandler {
            fetchHandler(query, page, completion)
        }
        
    }
}

class SearchTopUseCaseMock: SearchTopUseCase {
    init() { }


    var fetchCallCount = 0
    var fetchHandler: ((String) -> ())?
    func fetch(query: String)  {
        fetchCallCount += 1
        if let fetchHandler = fetchHandler {
            fetchHandler(query)
        }
        
    }
}

