///
/// @Generated by Mockolo
///



import Combine
import Foundation


class HomeUseCaseMock: HomeUseCase {
    init() { }


    var fetchCallCount = 0
    var fetchHandler: ((@escaping (Swift.Result<[Item], Error>) -> Void) -> ())?
    func fetch(completion: @escaping (Swift.Result<[Item], Error>) -> Void)  {
        fetchCallCount += 1
        if let fetchHandler = fetchHandler {
            fetchHandler(completion)
        }
        
    }
}

