///
/// @Generated by Mockolo
///



import Foundation


class HomeUseCaseMock: HomeUseCase {
    init() { }


    var fetchCallCount = 0
    var fetchHandler: ((Int, @escaping (Swift.Result<[Item], Error>) -> Void) -> ())?
    func fetch(page: Int, completion: @escaping (Swift.Result<[Item], Error>) -> Void)  {
        fetchCallCount += 1
        if let fetchHandler = fetchHandler {
            fetchHandler(page, completion)
        }
        
    }
}

